app/Models/User.php
<?php

namespace App\Models;

use App\Models\Exception\MessageException;
use App\Models\Interface\MessageInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Auth;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable, SoftDeletes;

    const ACCOUNT_STATUS_NONE = 1;
    const ACCOUNT_STATUS_DISABLED = 2;

    public $timestamps = true;

    protected $fillable = [
        'account_status',
        'address1',
        'address2',
        'city',
        'country',
        'email',
        'first_name',
        'language',
        'last_name',
        'password',
        'phone',
        'state',
        'timezone',
        'zip',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'deleted_at' => 'datetime',
        'email_verified_at' => 'datetime',
    ];

    // RELATIONSHIPS

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function students()
    {
        return $this->hasMany(Student::class);
    }

    public function trainers()
    {
        return $this->hasMany(Trainer::class);
    }

    public function organizations()
    {
        return $this->hasMany(Trainer::class);
    }

    // ACCESSORS

    public function getFullNameAttribute()
    {
        $full_name = $this->first_name;
        if (!is_null($this->last_name))
        {
            $full_name .= ' '.$this->last_name;
        }
        return $full_name;
    }

    public function getOrganizationMembershipsAttribute()
    {
        $organizations = [];
        foreach ($this->trainers as $trainer)
        {
            if ($trainer->organization)
            {
                $organizations[] = $trainer->organization;
            }
        }
        return $organizations;
    }

    // TOTEST
    public function getBookingRequestsAttribute()
    {
        $requests = [];
        foreach ($this->trainers as $trainer)
        {
            foreach ($trainer->booking_requests as $request)
            {
                $requests[] = $request;
            }
        }
        foreach ($this->organizations as $organization)
        {
            foreach ($organization->booking_requests as $request)
            {
                $requests[] = $request;
            }
        }
        return $requests;
    }

    // TOTEST
    public function getMessagesAttribute()
    {
        $messages = $this->getBookingRequestsAttribute();
        foreach ($messages as $message)
        {
            if (!$message instanceof MessageInterface)
            {
                throw new MessageException(MessageException::MESSAGE_PASSED_NOT_MESSAGE_MESSAGE,MessageException::MESSAGE_PASSED_NOT_MESSAGE_CODE);
            }
        }
        return $messages;
    }

    // TOTEST
    public function getUnreadMessagesAttribute()
    {
        $messages = $this->getMessagesAttribute();
        foreach ($messages as $key => $message)
        {
            if ($message->getRead())
            {
                unset($messages[$key]);
            }
        }
        return $messages;
    }

    // MISC

    public function hasRole(int $role_id): bool
    {
        return $this->roles->contains($role_id);
    }

    // STATIC

    public static function currentUser(Request $request): ?User
    {
        $user = Auth::user();

        if ($user && ($user->hasRole(Role::SUPERADMIN_ID) || $user->hasRole(Role::ADMIN_ID)))
        {
            $validated_data = $request->validate([
                'puser_id' => 'nullable|integer',
            ]);
            if (isset($validated_data['puser_id']))
            {
                $request->session()->put('puser_id',$validated_data['puser_id']);
            }
            if ($request->session()->get('puser_id',0) > 0)
            {
                $puser = User::find($request->session()->get('puser_id'));
                if ($puser)
                {
                    return $puser;
                }
            }
        }
        return $user;
    }
}

app/Http/Controllers/Coach/DashboardController.php
<?php

namespace App\Http\Controllers\Coach;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Trainer;

class DashboardController extends Controller
{
    public function showDashboard(Request $request)
    {
    	$params = [
    		'user' => $this->current_user,
    		'trainers' => $this->current_user->trainers,
    		'student_groups' => Trainer::getStudentGroups($this->current_user),
    	];
    	
    	return view('coach.pages.dashboard',$params);
    }
}

app/Http/Controllers/Coach/FieldController.php
<?php

namespace App\Http\Controllers\Coach;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Helpers\Helper;
use App\Models\Field;
use App\Models\Organization;
use App\Models\Trainer;

class FieldController extends Controller
{
    public function showFieldList(Request $request)
    {
        $validated_data = $request->validate([
            'list' => 'nullable|string',
            'sort' => 'nullable|string',
            'direction' => 'nullable|string|in:asc,desc',
        ]);

    	$field_groups = Trainer::getFieldGroups($this->current_user);
        $list = false;
        foreach ($field_groups as $group => $fields)
        {
            if (!$list)
            {
                $list = $group;
            }
        }
        if (isset($validated_data['list']))
        {
            $list = $validated_data['list'];
        }
        foreach ($field_groups as $group => $fields)
        {
            if ($group != $list)
            {
                $field_groups[$group] = [];
            }
        }
        $sort = isset($validated_data['sort']) ? $validated_data['sort'] : 'title';
        $direction = isset($validated_data['direction']) ? $validated_data['direction'] : 'asc';
        $is_asc = $direction === 'asc';

        $cols = [
            'title' => __('field.column_title'),
            'type_text' => __('field.column_type'),
        ];
        $col_data = [];
        foreach ($cols as $key => $title)
        {
            $tmp = new \stdClass;
            $tmp->key = $key;
            $tmp->title = $title;
            $tmp->sort = $sort === $key;
            $dir = $tmp->sort ? !$is_asc : 'asc';
            $tmp->direction = $dir ? 'asc' : 'desc';
            $tmp->arrow = $direction === 'asc' ? 'down' : 'up';
            $col_data[] = $tmp;
        }

        $all_fields = [];
        foreach ($field_groups as $group => $fields)
        {
            $all_fields = array_merge($all_fields,$fields);
        }
        usort($all_fields,function($a,$b) use ($sort,$is_asc){
            if ($is_asc)
            {
                return strcmp($a->$sort,$b->$sort);
            }
            return strcmp($b->$sort,$a->$sort);
        });

    	$params = [
    		'user' => $this->current_user,
    		'trainers' => $this->current_user->trainers,
    		'field_groups' => $field_groups,
            'all_fields' => $all_fields,
            'list' => $list,
            'query' => $validated_data,
            'columns' => $col_data,
    	];
    	
    	return view('coach.pages.field.list',$params);
    }

    public function showFieldNew(Request $request)
    {
        $validated_data = $request->validate([
            'o' => 'nullable|string',
        ]);

        $trainer_id = '';
        $organization_id = '';
        if (isset($validated_data['o']))
        {
            if (Helper::getNameFromGroup($validated_data['o']) === 'personal')
            {
                $id = Helper::getIDFromGroup($validated_data['o']);
                if ($id < 1)
                {
                    return redirect(route('coach.field.list'))->with('warning', __('notifications.invalid_address'));
                }
                $trainer = Trainer::find($id);
                if (!is_null($trainer) && !is_null($trainer->user) && $trainer->user->id === $this->current_user->id)
                {
                    $trainer_id = $trainer->id;
                }
                else
                {
                    return redirect(route('coach.field.list'))->with('warning', __('notifications.invalid_address'));
                }
            }
            else
            {
                $id = Helper::getIDFromGroup($validated_data['o']);
                if ($id < 1)
                {
                    return redirect(route('coach.field.list'))->with('warning', __('notifications.invalid_address'));
                }
                $organization = Organization::find($id);
                if (!is_null($organization) && $organization->hasTrainerUser($this->current_user))
                {
                    $organization_id = $organization->id;
                }
                else
                {
                    return redirect(route('coach.field.list'))->with('warning', __('notifications.invalid_address'));
                }
            }
        }
        else
        {
            return redirect(route('coach.field.list'))->with('warning', __('notifications.invalid_address'));
        }

        $params = [
            'user' => $this->current_user,
            'field' => null,
            'types' => Field::getTypeOptions(true),
            'trainer_id' => $trainer_id,
            'organization_id' => $organization_id,
            'list_option' => Field::TYPE_LIST,
        ];
        
        return view('coach.pages.field.edit',$params);
    }

    public function showFieldEdit(Request $request, $id)
    {
        $field = Field::find($id);
        if (is_null($field) || !$field->hasTrainerUser($this->current_user))
        {
            return redirect(url('/'))->with('warning', __('notifications.invalid_address'));
        }
        $list = '';
        if (!is_null($field->trainer_id))
        {
            $list = 'personal|'.$field->trainer_id;
        }
        else if (!is_null($field->organization_id))
        {
            $list = $field->organization->name.'|'.$field->organization_id;
        }

        $params = [
            'user' => $this->current_user,
            'field' => $field,
            'types' => Field::getTypeOptions(true),
            'trainer_id' => null,
            'organization_id' => null,
            'list' => $list,
            'list_option' => Field::TYPE_LIST,
        ];
        
        return view('coach.pages.field.edit',$params);
    }

    public function saveField(Request $request)
    {
        $validated_data = $request->validate([
            'id' => 'nullable|integer',
            'trainer_id' => 'nullable|integer',
            'organization_id' => 'nullable|integer',
            'title' => 'string',
            'type' => 'string',
            'display_students_list' => 'boolean',
            'options' => 'nullable|array',
            'options_list_text' => 'nullable|string',
        ]);

        if (isset($validated_data['organization_id']))
        {
            $organization = Organization::find($validated_data['organization_id']);
            if (is_null($organization) || !$organization->hasTrainerUser($this->current_user))
            {
                return redirect(url('/'))->with('warning', __('notifications.invalid_address'));
            }
        }
        if (isset($validated_data['trainer_id']))
        {
            $trainer = Trainer::find($validated_data['trainer_id']);
            if (is_null($trainer) || $trainer->user_id !== $this->current_user->id)
            {
                return redirect(url('/'))->with('warning', __('notifications.invalid_address'));
            }
        }

        if (!isset($validated_data['display_students_list']))
        {
            $validated_data['display_students_list'] = false;
        }

        if (isset($validated_data['options_list_text']))
        {
            $validated_data['options']['list'] = $validated_data['options_list_text'];
        }

        if (!isset($validated_data['id']))
        {
            if (isset($validated_data['trainer_id']) xor isset($validated_data['organization_id']))
            {
                $field = Field::create($validated_data);
            }
            else {
                return redirect(url('/'))->with('warning', __('notifications.invalid_address'));
            }
        }
        else
        {
            $field = Field::find($validated_data['id']);
            if (is_null($field) || !$field->hasTrainerUser($this->current_user))
            {
                return redirect(url('/'))->with('warning', __('notifications.invalid_address'));
            }
            $field->update($validated_data);
        }

        return redirect(route('coach.field.edit',['id' => $field->id]))->with('success', __('field.saved_field'));
    }

    public function deleteField(Request $request, $id)
    {
        $field = Field::find($id);
        if (is_null($field) || !$field->hasTrainerUser($this->current_user))
        {
            return redirect(url('/'))->with('warning', __('notifications.invalid_address'));
        }

        $field->delete();

        return redirect(route('coach.field.list'))->with('success', __('field.deleted_field'));
    }
}

app/Http/Controllers/Coach/TrainerController.php
<?php

namespace App\Http\Controllers\Coach;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TrainerController extends Controller
{
    //
}

resources/views/coach/modules/alerts.blade.php
@foreach (Helper::getNotifications() as $type => $class)
	@if (Session::has($type))
	<x-b-element.notification :type="$class">{{Session::get($type)}}</x-b-element.notification>
	@endif
@endforeach

resources/views/coach/modules/footer.blade.php
<footer class="footer">
	<div class="container">
		<p>{!!__('brand.copyright', ['year' => date('Y')])!!}</p>
	</div>
</footer>

resources/views/coach/modules/head-content.blade.php
{{--
	Include general <head> content common to all pages here.
--}}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">

<link rel="shortcut icon" type="image/ico" href="/favicon.ico">

resources/views/coach/modules/header.blade.php
<header>
	<nav class="navbar is-spaced is-dark" role="navigation" aria-label="main naviagation">
		<div class="navbar-brand">
			<a class="navbar-item" href="/">
				<img src="/images/logo.png" width="283" height="25" alt="{{__('brand.name')}}">
			</a>

			<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="main-menu">
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
			</a>
		</div>
		<div class="navbar-menu" id="main-menu">
			<div class="navbar-start">
				<a href="{{route('coach.dashboard')}}" class="navbar-item">{{__('misc.dashboard')}}</a>
				<div class="navbar-item has-dropdown is-hoverable">
					<a class="navbar-link" href="{{route('coach.organization.list')}}">{{__('organization.organizations')}}</a>
					<div class="navbar-dropdown">
						<a class="navbar-item">{{__('misc.list')}}</a>
						<a class="navbar-item">{{__('misc.list')}}</a>
						<a class="navbar-item">{{__('misc.list')}}</a>
						<hr class="navbar-divider">
						<a class="navbar-item">{{__('misc.help')}}</a>
					</div>
				</div>
				<div class="navbar-item has-dropdown is-hoverable">
					<a class="navbar-link" href="{{route('coach.student.list')}}">{{__('student.students')}}</a>
					<div class="navbar-dropdown">
						<a class="navbar-item">{{__('misc.list')}}</a>
						<a class="navbar-item">{{__('misc.list')}}</a>
						<a class="navbar-item">{{__('misc.list')}}</a>
						<hr class="navbar-divider">
						<a class="navbar-item">{{__('misc.help')}}</a>
					</div>
				</div>
				<a href="{{route('coach.field.list')}}" class="navbar-item">{{__('field.fields')}}</a>
			</div>
			<div class="navbar-end">
				<a href="{{route('messages')}}" class="messages navbar-item is-hidden-touch" title="{{__('message.messages_unread_x',['count' => count($user->unread_messages)])}}"><x-b-element.icon icon="mail" color="light" class="icon is-left"/>
				@if (!empty($user->unread_messages))
					<span class="messages-indicator button is-secondary is-rounded is-small">{{count($user->unread_messages)}}
				@endif
				</a>
				<div class="navbar-item has-dropdown is-hoverable">
					<a class="navbar-link">{{$user->full_name}}</a>
					<div class="navbar-dropdown">
						<a class="navbar-item">{{__('misc.settings')}}</a>
						<a class="navbar-item">{{__('user.linked_accounts')}}</a>
						<hr class="navbar-divider">
						<a class="navbar-item" href="{{route('logout')}}"><strong>{{__('user.logout')}}</strong></a>
					</div>
				</div>
			</div>
		</div>
	</nav>
</header>

resources/views/coach/modules/scripts.blade.php
{{--
	Include Javscript common to all pages here.
--}}

<x-assets.jquery/>

<x-assets.flatpickr/>

<script src="{{asset(Helper::autoversion('/js/concat/coach-combined.js'))}}" type="text/javascript"></script>

@stack('scripts')

resources/views/coach/modules/styles.blade.php
{{--
	Include Styles common to all pages here.
--}}

<link href="https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

<link href="{{asset(Helper::autoversion('/css/coach-combined.min.css'))}}" rel="stylesheet" type="text/css">